name: CI

on: [ push ]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    continue-on-error: ${{ matrix.php-versions == '8.6' }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]
        php-versions: [ '8.2', '8.3', '8.4', '8.5', '8.6' ]
    name: PHP ${{ matrix.php-versions }} ${{ matrix.operating-system }}
    steps:
      - name: Git Configure
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: intl #optional
          ini-values: "post_max_size=256M" #optional
          coverage: none
      - name: Validate composer.json and composer.lock
        run: composer validate
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction --ignore-platform-reqs
      - name: PHPUnit
        run: vendor/bin/phpunit
      - name: PHPCS
        run: vendor/bin/phpcs --standard=psr12 src/ -s
      - name: PHPStan
        if: matrix.operating-system == 'ubuntu-latest'
        run: vendor/bin/phpstan analyse
  coverage:
    name: Coverage Reports
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: intl #optional
          ini-values: "post_max_size=256M" #optional
          coverage: xdebug
      - name: Prepare FS
        run: mkdir -p build/logs
      - name: Validate composer.json and composer.lock
        run: composer validate
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction --ignore-platform-reqs
      - name: PHPUnit
        run: vendor/bin/phpunit --coverage-clover build/logs/clover.xml
      - name: Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          composer global require php-coveralls/php-coveralls
          php-coveralls --coverage_clover=build/logs/clover.xml -v
